### ISSUE TITLE
This package fails to load my analyzer (but hfst succeeds)

### ISSUE THREAD

**Issue by bowersd** [Rootroo-ltd/pyhfst#3]
When I call this:

parser = pyhfst.HfstInputStream("name_of_transducer.hfst").read()

pyhfst throws an error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 1: invalid start byte 

The parallel call with hfst works:

parser = hfst.HfstInputStream("name_of_transducer.hfst").read()

I tried opening the transducer as a byte stream and passing that to pyhfst.HfstInputStream(), but that threw an error claiming that bytes, strings or file names were expected, not BufferedReader objects.

**Comment by bowersd** [comment]
Running this on hfst vs hfstol files produces different errors. hfstol throws a list index out of range error as it tries to initialize the transducer alphabet. Is there a pyhfst-internal way to compile transducers that does not produce this error?

**Comment by mikahama** [comment]
Is your transducer weighted or unweighted? We mainly deal with weighted transducers. Can you send us your transducer in optimized lookup format and an example input and expected output?

**Comment by bowersd** [comment]
[hfst.zip](https://github.com/Rootroo-ltd/pyhfst/files/14379744/hfst.zip)

It should be weighted. I am pretty sure I put some weights in the source code a while ago. I have included both an hfst file and an hfstol file.

input: mkizin
expected output: mkizin+NI, mkizin+NA

**Comment by mokha** [comment]
Issue identified and fixed in a425d53 and in pyhfst==1.2.0
