### ISSUE TITLE
pyhfst fails to load basic hfst file (but succeeds on optimized lookup aka hfstol)

### ISSUE THREAD

**Issue by bowersd** [Rootroo-ltd/pyhfst#7]
pyhfst crashes when loading an hfst file, as shown in the attached screenshot. It succeeds when loading an optimized lookup version of the hfst file. Hfst of course loads both versions without trouble.
![pyhfst_error](https://github.com/Rootroo-ltd/pyhfst/assets/6401700/d46c9af5-8d11-44ae-85a9-8e6424eee490)

I attach the troubled hfst file as well.
[morphophonologyclitics_analyze.hfst.zip](https://github.com/user-attachments/files/15687621/morphophonologyclitics_analyze.hfst.zip)

**Comment by mikahama** [comment]
Pyhfst does not support regular hfst files, only optimized lookup files. Even the readme says this

**Comment by bowersd** [comment]
Ah, I see what you are talking about in the readme. For what it is worth, as I read it, the readme only says that it makes it possible to use transducers in optimized format. It might be helpful to explicitly say that pyhfst only supports optimized transducers. Just a thought.
